{{- range .Values.persistence }}
{{- if and .enabled (not .existingClaim) (eq "pvc" .type)}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "audiobookshelf.fullname" $ }}-{{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "audiobookshelf.labels" $ | nindent 4 }}
{{- with .annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:  
  accessModes:
    - {{ .accessMode | quote }}
  resources:
    requests:
      storage: {{ .size }}
{{- if .storageClass }}
{{- if (eq "-" .storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .storageClass }}"
{{- end }}
{{- end }}
---
{{- end }}
{{- end }}